// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250131094743_UpdateName")]
    partial class UpdateName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telefon Açıklaması",
                            ImgUrl = "1.jpg",
                            IsActive = true,
                            Name = "ABC",
                            Price = 50000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Telefon Açıklaması",
                            ImgUrl = "2.jpg",
                            IsActive = true,
                            Name = "ABC 2",
                            Price = 32000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Description = "Telefon Açıklaması",
                            ImgUrl = "3.jpg",
                            IsActive = false,
                            Name = "ABC 3",
                            Price = 40000m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
